version: '3'
services:
  example:
    container_name: secyan_example_server
    image: sirily11/secyan_python
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - ./:/usr/local/project
    environment:
      - address=example
    command: python3 /usr/local/project/src/python_example/tpch.py