version: '3'
services:
#  mysql:
#    container_name: flask_mysql
#    restart: always
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: 'pass'
#      MYSQL_USER: 'test'
#      MYSQL_PASS: 'pass'
#    volumes:
#      - my-datavolume:/var/lib/mysql
  dev:
    container_name: secyan_dev
    command: "/usr/sbin/sshd -D -e -f /etc/ssh/sshd_config_test_clion"
    ports:
    - "2222:22"
    build:
      dockerfile: docker/.dockerfile
      context: ./
    volumes:
      - ./:/usr/local/project
  demo:
    container_name: secyan_demo
    command: "gcc -v"
    build:
      dockerfile: docker/demo.dockerfile
      context: ./