version: '3'
services:
  dev:
    container_name: secyan_dev
    command: "/usr/sbin/sshd -D -e -f /etc/ssh/sshd_config_test_clion"
    ports:
    - "2222:22"
    build:
      dockerfile: docker/.dockerfile
      context: ./
    volumes:
      - ./:/usr/local/project
  demo:
    container_name: secyan_demo
    command: "g++ -v"
    build:
      dockerfile: docker/demo.dockerfile
      context: ./