version: '3'
services:
  build:
    container_name: secyan_build
    image: sirily11/secyan_python
    build:
      dockerfile: docker/Dockerfile
      context: ./
    volumes:
      - ./:/usr/local/project
    environment:
      - build_dir=/usr/local/project/docker-build
      - output_dir=/usr/local/project/docker-output