name: Build Release

on: push
#  release:
#    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.8]
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - run: brew install openssl
    - run: brew install gmp
    - run: brew install boost
    - run: brew install pybind11
    - run: brew install ninja
    - run: python3 -m pip install --upgrade build
    - run: python3 -m pip install --upgrade twine
    - name: Build Output
      uses: pypa/cibuildwheel@v2.1.1
    - name: Publish
      run: python3 -m twine upload dist/*
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_USERNAME: __token__



