name: Build Release

on:
  release:
    types: [published]

jobs:
  macOS:
    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.9]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - run: brew install openssl
    - run: brew install gmp
    - run: brew install boost
    - run: brew install pybind11
    - run: brew install ninja
    - run: python3 -m pip install --upgrade build
    - name: Build Output
      run: python3 -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

